services:
  - type: web
    name: question-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: proxy
        source: /api/*
        destination: https://question-api-75d6.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
